# Generated by Django 5.1.1 on 2024-10-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0009_emailaddress_unique_primary_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("course", models.CharField(max_length=255)),
                ("due_date", models.DateTimeField()),
                ("platform", models.CharField(default="Canvas", max_length=255)),
                ("points", models.IntegerField()),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="account.emailaddress",
                    ),
                ),
            ],
        ),
    ]
