# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
    - name: Install dependencies
      run: |
          npm install --save-dev jest
          npm install --save-dev @testing-library/react @testing-library/dom
          npm install --save-dev eslint-config-prettier
          npm install --save @chakra-ui/react
          npm install react-router-dom
    - name: Run Tests
      run: |
          cd frontend/src
          npm run test



    
